### ISSUE TITLE
run:proxy command is not supported in "linux"

### ISSUE THREAD

**Issue by davidquinto** [ara-framework/ara-cli#41]
I tried to run this command:
`ara run:proxy --config ./nova-proxy.json`

But this error appears:
`run:proxy command is not supported in "linux"`

* **Platform**: Ubuntu 18.04.4 LTS
* **Platform**: Linux 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* **ara-cli version**: 1.0.0-alpha.4

**Comment by marconi1992** [comment]
Fixed @davidquinto, Thanks for the heads up! You need to just get the latest version

**Comment by davidquinto** [comment]
@marconi1992 It works. Thanks you!
