### ISSUE TITLE
Cli & docker questions

### ISSUE THREAD

**Issue by francjpd** [ara-framework/ara-cli#7]
Hello Felipe,

First & foremost, Congratulations on the entire project you've been working on. 

I´ve been reading the whole documentation and i saw you´re still working on it, how ever if you can enlighten me a bit i would appreciate it.

1. At the CLI, there is an option about creating a project. What´s the purpose of it ?Is it to have a local environment to test your Nova view ?

2. I've seen you're using your own docker images, what's inside of them? It would be good if you provided a little description about them.

**Comment by marconi1992** [comment]
Hi Francisco. Good catch!!

I need to deprecate that command. The command basically creates a local environment using docker images for Nova [Cluster](https://github.com/ara-framework/nova-cluster) and [Proxy](https://github.com/ara-framework/nova-proxy).

You can read more about the Nova architecture [here](https://ara-framework.github.io/website/docs/nova-architecture).

The main goal of that command was to create a project with a basic setup to easily implement the architecture. However, It'll be deprecated in favor of cli commands against docker containers.

The documentation has an example of how to implement Nova Proxy using the CLI 
https://ara-framework.github.io/website/docs/render-on-page

The command to run Nova Cluster is still pending, for that reason, I didn't  remove the command yet.

**Comment by francjpd** [comment]
Yup, i pretty much understood your documentation :)

My problem was when i was checking your code to see how you did it  (Ops !) and saw your own [container images](https://github.com/ara-framework/ara-cli/blob/1e0b5207a795bbc93a3be515fc725f35a7bad48c/src/generators/project/template/.ara/proxy/Dockerfile#L1).  So the 2nd question was about this, what is inside these containers? A Brief overview about each container would be awesome :), (I looked at the (docker hub)[https://hub.docker.com/r/marconi1992/hypernova-proxy ] but theres isn't any description either 

PD: I  totally understand if it does not have any, I suppose its an enormous project for one person to do everything.

PD2: You can close the issue as you already answered to my main question. :)

Best regards
